apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datasafe.storageServer.fullname" . }}
  labels:
    {{- include "datasafe.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage-server
type: Opaque
stringData:
  STORAGE_SECRET_KEY: {{ .Values.storageServer.config.secretKey | quote }}
  STORAGE_ADMIN_PASSWORD: {{ .Values.storageServer.config.adminPassword | quote }}
  STORAGE_JWT_SECRET: {{ .Values.storageServer.config.jwtSecret | quote }}
  {{- if .Values.storageServer.config.sseMasterKey }}
  STORAGE_SSE_MASTER_KEY: {{ .Values.storageServer.config.sseMasterKey | quote }}
  {{- end }}
  {{- if or .Values.postgres.enabled (eq (include "datasafe.metadataBackend" .) "postgres") }}
  STORAGE_POSTGRES_PASSWORD: {{ .Values.storageServer.config.postgres.password | default .Values.postgres.auth.password | quote }}
  {{- if .Values.storageServer.config.postgres.dsn }}
  STORAGE_POSTGRES_DSN: {{ .Values.storageServer.config.postgres.dsn | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.ldap.enabled }}
  STORAGE_LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
  {{- end }}
  {{- if .Values.oidc.enabled }}
  STORAGE_OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.logging.elasticsearch.enabled }}
  {{- if .Values.logging.elasticsearch.password }}
  LOGGING_ELASTICSEARCH_PASSWORD: {{ .Values.logging.elasticsearch.password | quote }}
  {{- end }}
  {{- if .Values.logging.elasticsearch.token }}
  LOGGING_ELASTICSEARCH_TOKEN: {{ .Values.logging.elasticsearch.token | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.logging.loki.enabled }}
  {{- if .Values.logging.loki.token }}
  LOGGING_LOKI_TOKEN: {{ .Values.logging.loki.token | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.logging.webhook.enabled }}
  {{- if .Values.logging.webhook.token }}
  LOGGING_WEBHOOK_TOKEN: {{ .Values.logging.webhook.token | quote }}
  {{- end }}
  {{- end }}
